name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Vishalpatil0111
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          
      - name: Push Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist
